# Numpy

In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#Dimension of Array 
import numpy as np

#0 dimension array
arr=np.array(42)
print(arr)

#1 Dimension array
arr1=np.array([1,2,3,4])
print(arr1)

#2 Dimension array
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print("This is 2 dimension array",arr2)

#3 Dimension array
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("This is 3 dimension array",arr3)

42
[1 2 3 4]
This is 2 dimension array [[1 2 3 4]
 [5 6 7 8]]
This is 3 dimension array [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
#Creating an array with 5 dimension using "ndim"

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [10]:
#Indexing in Araray

#indexing in 1 dimension array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

#indexing in 2 dimension array
import numpy as np

arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr1[1, 4])

#indexing in 3 dimension array
import numpy as np

arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr2[0, 1, 2])

2
5th element on 2nd row:  10
6


In [1]:
#Slicing in Array 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

#Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

#Negative Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

#STEP   "Return every other element from index 1 to index 5:"
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

#Slicing 2-D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[2 3 4 5]
[5 6 7]
[5 6]
[2 4]
[7 8 9]


In [3]:
#Shape of an Array
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#Flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6]


In [5]:
#Practice Challenge : Create a 10x10 matrix / Replace diagonals with 1 / Normalize between 0–1 Extract all prime numbers from it

import numpy as np

# Step 1: Create 10x10 random integer matrix
matrix = np.random.randint(0, 100, (10, 10))
print("Original Matrix:\n", matrix)

# Step 2: Replace both diagonals with 1
for i in range(10):
    matrix[i, i] = 1                      # Main diagonal
    matrix[i, 9 - i] = 1                  # Anti-diagonal

print("\nMatrix with Diagonals Replaced:\n", matrix)

# Step 3: Normalize between 0 and 1
min_val = matrix.min()
max_val = matrix.max()

normalized_matrix = (matrix - min_val) / (max_val - min_val)
print("\nNormalized Matrix:\n", normalized_matrix)

# Prime-check helper
def is_prime(n):
    if n < 2: return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0: return False
    return True

# Step 4: Extract primes from the original matrix
primes = [num for row in matrix for num in row if is_prime(num)]
print("\nPrime Numbers in Matrix:\n", primes)


Original Matrix:
 [[54 40 27 97 63 51 31 30 27  5]
 [78 48 43 35 66 57 19 41 67  6]
 [ 1 67 84 12  0 25 84 44  8 38]
 [53  1 14 13  9 14 74 90 16 19]
 [22  4 71 69 59 27  0 95 37 23]
 [61 61 68 45 71 83 22 51 93 87]
 [ 3 89 40 71 30 32  8  7 91 68]
 [77 29 58  0 79 60 51  2  6 17]
 [77  4 56  2 18 78 17 40 91  8]
 [15  5 34 27 21 16 89 49  7 67]]

Matrix with Diagonals Replaced:
 [[ 1 40 27 97 63 51 31 30 27  1]
 [78  1 43 35 66 57 19 41  1  6]
 [ 1 67  1 12  0 25 84  1  8 38]
 [53  1 14  1  9 14  1 90 16 19]
 [22  4 71 69  1  1  0 95 37 23]
 [61 61 68 45  1  1 22 51 93 87]
 [ 3 89 40  1 30 32  1  7 91 68]
 [77 29  1  0 79 60 51  1  6 17]
 [77  1 56  2 18 78 17 40  1  8]
 [ 1  5 34 27 21 16 89 49  7  1]]

Normalized Matrix:
 [[0.01030928 0.41237113 0.27835052 1.         0.64948454 0.5257732
  0.31958763 0.30927835 0.27835052 0.01030928]
 [0.80412371 0.01030928 0.44329897 0.36082474 0.68041237 0.58762887
  0.19587629 0.42268041 0.01030928 0.06185567]
 [0.01030928 0.69072165 0.01030928 0